spring:
  application:
    name: cm4sb-card-client

  jackson:
    # property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
    # property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.PascalCaseStrategy
    # property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.UpperCamelCaseStrategy
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true


management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  #        include: ["info", "health", "prometheus", "chaosmonkey"]
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
#      sla:
#        http.server.requests: 100ms, 200ms, 400ms

server:
  port: 8090
